### ISSUE TITLE
Fresh install of hood.ie and global-share plugin rejects the promises

### ISSUE THREAD

**Issue by mart-jansink** [hoodiehq-archive/hoodie-plugin-global-share#19]
Using a fresh install of the latest version of hood.ie with this plugin doesn't seem to work out-of-the-box. Trying the example code from the docs on the hoodie playground, `hoodie.store.findAll('todo').publish()` gives an `unhandled promise rejection error` (using Chrome). Digging deeper with `hoodie.store.findAll('todo').publish().fail(console.log.bind(console))` shows that this is caused by a TypeError `Cannot read property 'then' of undefined` in `exports.updateAll (http://localhost:6001/_api/_files/hoodie.js:9569:20)`.

I'm unable to locate this exact hoodie.js file in the source as it seems that the hoodie module is installed multiple times at several locations in the node_modules directory (also, different versions are installed as this plugin depends on hoodie 0.6.5 while 1.0.1 is already out?). Seeing that the `.publish()` function only sets `{public: true}`, I tried `hoodie.store.updateAll('todo',{$public:true}).done(console.log.bind(console))` which had the expected effect of triggering the plugin's worker to replicate the document.

**Comment by gr2m** [comment]
Hey @mart-jansink, thanks for reporting the issue! I'll look into it later today.

**Comment by gr2m** [comment]
@mart-jansink I just created a new hoodie app, and the app has `"hoodie-server": "^2.0.0"` as dependency which loades hoodie@1.0.1. Could you try the following

```
npm cache clean
npm i -g hoodie-cli
```

That should make sure you get the right version for the next app. For the current app, you can update the package.json manually.

But despite using the latest hoodie.js version, I still get the `Cannot read property 'then' of undefined` error. Still checking this one

**Comment by gr2m** [comment]
@mart-jansink Thanks so much Mart, there was in fact a bug in `hoodie.store.updateAll` which I could fix thanks to your report :) The fix will land in hoodie@1.0.2, which should be published in a few minutes

**Comment by mart-jansink** [comment]
I didn't get round to testing it earlier, but it is indeed fixed, thanks! I'm however still slightly puzzled by the fact that while installing the global-share plugin it also installs an older version of `hoodie` and `hoodie-server`:

```
[hoodie] Installing plugin(s): global-share
hoodie-plugin-global-share@3.0.0 node_modules/hoodie-plugin-global-share
├── async@0.2.10
├── lodash@2.4.1
├── hoodie@0.6.5 (extend@1.2.1)
└── hoodie-server@0.9.19
```

Are these versions actually used?

**Comment by gr2m** [comment]
hmm that is odd, I'll ping the backend people on this :)

**Comment by gr2m** [comment]
So, hoodie & hoodie-server are [listed as dependencies](https://github.com/hoodiehq/hoodie-plugin-global-share/blob/master/package.json#L13-L14) but that doesn't make any sense, really :) We'l get rid of it. They definitely are not used in your app

**Comment by janl** [comment]
they are dev dependencies, so we can test the full stack :)
