### ISSUE TITLE
[pocket] 404 in plugin view

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/hoodie-plugin-global-share#9]
The pocket folder including an index.html is missing in the plugin, so there is a 404 shown in the pocket admin panel iframe.

We should add a pocket folder and discuss if a pocket folder is a requirement... if not, no 404 should be shown.

**Comment by gr2m** [comment]
I'd say if there is now pocket folder, it should have no view in pocket at all. The pocket folder should not be a requirement.

**Comment by zoepage** [comment]
Cool. I'll take care of it in the next pocket release. :)

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/pocket/issues/46
